[project]
name = "ls-base"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jianglai", email = "lingxg2024@lzu.edu.cn" }
]
requires-python = ">=3.14"
dependencies = [
    "dashscope>=1.26.6",
    "ipywidgets>=8.1.8",
    "langchain>=1.3.14",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.3",
    "langchain-deepseek>=1.1.0",
    "langchain-openai>=1.4.2",
    "langchain-tavily>=0.2.18",
    "notebook>=7.6.1",
    "openai>=2.53.0",
]

[project.scripts]
ls-base = "ls_base:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
